# Author: Monil Hitesh Andharia (B00884813)

image: node:latest

stages:
  - deploy

deploy_prod:
  stage: deploy
  script:
    - npm install
    - npm install netlify-cli -g
    - netlify deploy --auth $NETLIFY_AUTH_TOKEN --dir 'dist' --site $SITE_ID_PROD --prod
  only:
    - main

deploy_develop:
  stage: deploy
  script:
    - npm install
    - npm install netlify-cli -g
    - netlify deploy --auth $NETLIFY_AUTH_TOKEN --dir 'dist' --site $SITE_ID_DEVELOP --prod
  only:
    - develop

deploy_monil:
  stage: deploy
  script:
    - npm install
    - npm install netlify-cli -g
    - netlify deploy --auth $NETLIFY_AUTH_TOKEN --dir 'dist' --site $SITE_ID_MONIL --prod
  only:
    - main-monil
